### ISSUE TITLE
Not Working for me in xCode Version 6.3.2 (6D2105)

### ISSUE THREAD

**Issue by narlei** [kimsungwhee/KSHObjcUML#10]
Is not showing for me in Menu. I deleted the plugin and reinstalled it.

**Comment by kimsungwhee** [comment]
I guess,your xcode blocked plugins.
![mzmyd](https://cloud.githubusercontent.com/assets/646158/7928009/b7dd39d2-0923-11e5-94b6-f3b2b8feed85.png)

if you click [Skip Bundle] button,plugin will be blocked.

try this command at terminal.

defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2

or

http://stackoverflow.com/questions/30361228/why-are-my-xcode-plugins-such-as-clang-format-installed-with-alcatraz-no-longe

**Comment by kimsungwhee** [comment]
thanks.this is bug.
i had fixed.
please reinstall latest version.
