### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by ipoolo** [kimsungwhee/KSHObjcUML#12]
ind: /Users/*****_/Library/Caches/appCode_/DerivedData: No such file or directory
There were 10 directories found
Last modifications were in
/Users/liupoolo/Library/Developer/Xcode/DerivedData/ParkingWang-cruhyperywkpgfelorgnwogyynpn/Build/Intermediates/ParkingWang.build/Debug-iphonesimulator/ParkingWang.build/Objects-normal/x86_64
directory at
2015-07-14 16:27:50 +0800
sh: line 1: 12404 Abort trap: 6           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find nm 2> /dev/null
nm: error: unable to find utility "nm", not a developer tool or in PATH

xcode 6.4

**Comment by kimsungwhee** [comment]
Please install Xcode Command Line Tools.

https://developer.apple.com/downloads/

**Comment by ipoolo** [comment]
thxs
