### ISSUE TITLE
关于KSHObjcUML项目的求解

### ISSUE THREAD

**Issue by ghost** [kimsungwhee/KSHObjcUML#15]
您好：
    看了您的KSHObjcUML项目以及您所参考的cocoapods-xcode-plugin和objc-dependency-visualizer两个项目。我提取了程序中类之间的依赖关系，从代码实现的角度上查看项目中类依赖关系是否符合当初架构设计的规则；

```
目前我想基于您的项目结合代码评审规则；将此项目做成代码评审工具，甚至把它做成代码自动化评审工具，极大的简化开发中代码评审这个环节；

但是目前此项目只能提取类级别的依赖关系，我想要提取更精细的依赖关系。
因此询问你三个问题：
1、这个项目下一步的发展是否要提取精确到类方法级别的依赖关系？
2、不知道您是否用过微软VS的code map功能？地址如下：https://msdn.microsoft.com/zh-cn/library/dd409453.aspx；很希望在iOS平台上也有这么一款插件。
3、我看了源码，获取类依赖的核心代码，是用ruby写的，因为这个语言我不懂，所以还没能理解到你提取类依赖关系的原理？
我先大致的说一下我的理解：程序编译后，生成目标app，然后使用某种方式对目标app进行类依赖关系的解析；
我对解析目标app类依赖关系这个环节，有些疑问。这个环节的实现原理是什么？oc语言的语法、还是注册某种代码到目标app中，然后通过某种方式提取类依赖关系？方便的话，是否可以介绍给我些相关的资料。

希望您的项目能够给广大的开发者带来更多的惊喜。   

    期待您的答复。

    我的联系方式：176290392@qq.com
```

**Comment by kimsungwhee** [comment]
你好，基本上这个项目的核心方法是通过使用Xcode Tools的nm命令，你可以参考一下如下地址：
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/nm.1.html

如果要是想提取方法的话也是可能的。比如如下：

<pre>
$ /usr/bin/nm -o ./KSHCameraViewController.o
./KSHCameraViewController.o: 0000000000002890 t -[KSHCameraViewController .cxx_destruct]
./KSHCameraViewController.o: 00000000000000a0 t -[KSHCameraViewController cameraController]
./KSHCameraViewController.o: 00000000000025b0 t -[KSHCameraViewController cameraFlashButton]
./KSHCameraViewController.o: 0000000000002790 t -[KSHCameraViewController cameraSwitchButton]
./KSHCameraViewController.o: 0000000000000000 t -[KSHCameraViewController dealloc]
./KSHCameraViewController.o: 0000000000000980 t -[KSHCameraViewController didReceiveMemoryWarning]
./KSHCameraViewController.o: 0000000000000de0 t -[KSHCameraViewController filterEnableButtonPressed:]
./KSHCameraViewController.o: 00000000000023e0 t -[KSHCameraViewController observeValueForKeyPath:ofObject:change:context:]
./KSHCameraViewController.o: 0000000000002810 t -[KSHCameraViewController overlayView]
./KSHCameraViewController.o: 00000000000009c0 t -[KSHCameraViewController prefersStatusBarHidden]
./KSHCameraViewController.o: 0000000000000130 t -[KSHCameraViewController previewView]
./KSHCameraViewController.o: 0000000000000c50 t -[KSHCameraViewController recordButtonPressed:]
./KSHCameraViewController.o: 0000000000002530 t -[KSHCameraViewController setCameraController:]
./KSHCameraViewController.o: 00000000000025f0 t -[KSHCameraViewController setCameraFlashButton:]
./KSHCameraViewController.o: 00000000000027d0 t -[KSHCameraViewController setCameraSwitchButton:]
./KSHCameraViewController.o: 0000000000002850 t -[KSHCameraViewController setOverlayView:]
./KSHCameraViewController.o: 0000000000002570 t -[KSHCameraViewController setPreviewView:]
./KSHCameraViewController.o: 00000000000026d0 t -[KSHCameraViewController setTimer:]
./KSHCameraViewController.o: 0000000000002670 t -[KSHCameraViewController setTimerLabel:]
./KSHCameraViewController.o: 0000000000002750 t -[KSHCameraViewController setTimerViewTopConstraint:]
./KSHCameraViewController.o: 0000000000001cf0 t -[KSHCameraViewController startTimer]
./KSHCameraViewController.o: 0000000000001fe0 t -[KSHCameraViewController stopTimer]
./KSHCameraViewController.o: 0000000000000b80 t -[KSHCameraViewController switchCameraButtonPressed:]
./KSHCameraViewController.o: 00000000000009e0 t -[KSHCameraViewController switchFlashButtonPressed:]
./KSHCameraViewController.o: 0000000000002310 t -[KSHCameraViewController tappedToExposeAtPoint:]
./KSHCameraViewController.o: 00000000000022a0 t -[KSHCameraViewController tappedToFocusAtPoint:]
./KSHCameraViewController.o: 0000000000002380 t -[KSHCameraViewController tappedToResetFocusAndExposure]
./KSHCameraViewController.o: 0000000000002630 t -[KSHCameraViewController timerLabel]
./KSHCameraViewController.o: 0000000000002710 t -[KSHCameraViewController timerViewTopConstraint]
./KSHCameraViewController.o: 00000000000026b0 t -[KSHCameraViewController timer]
./KSHCameraViewController.o: 0000000000002090 t -[KSHCameraViewController updateFlashButtonByTochMode:]
./KSHCameraViewController.o: 0000000000000fb0 t -[KSHCameraViewController updateOverLayer]
./KSHCameraViewController.o: 0000000000001e40 t -[KSHCameraViewController updateTimeDisplay]
./KSHCameraViewController.o: 00000000000002d0 t -[KSHCameraViewController viewDidLoad]
./KSHCameraViewController.o:                  U _AVCaptureSessionPreset1280x720
./KSHCameraViewController.o:                  U _CGAffineTransformIdentity
./KSHCameraViewController.o:                  U _CGAffineTransformMakeTranslation
./KSHCameraViewController.o: 00000000000076c8 d _CameraTorchModeObservationContext
./KSHCameraViewController.o:                  U _NSLog
./KSHCameraViewController.o:                  U _NSRunLoopCommonModes
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_KSHCameraController
./KSHCameraViewController.o: 00000000000075f0 S _OBJC_CLASS_$_KSHCameraViewController
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_KSHContextManager
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_KSHPreviewView
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_NSRunLoop
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_NSString
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_NSTimer
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_UIImage
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_UIView
./KSHCameraViewController.o:                  U _OBJC_CLASS_$_UIViewController
</pre>

**Comment by ghost** [comment]
非常感谢！
