### ISSUE TITLE
类太多了，怎么才能让图整齐起来？

### ISSUE THREAD

**Issue by wushuyu** [kimsungwhee/KSHObjcUML#16]
![image](https://cloud.githubusercontent.com/assets/15336035/11629981/24f7dc92-9d36-11e5-9ff2-d200db82099b.png)
![image](https://cloud.githubusercontent.com/assets/15336035/11629998/3c497324-9d36-11e5-8817-a69cd3a2ec99.png)
![image](https://cloud.githubusercontent.com/assets/15336035/11630011/4ff307e6-9d36-11e5-8a62-7ca5cd3d6b0f.png)

**Comment by wushuyu** [comment]
不用解决啦，我已经搞定了。在 project_dir/ObjcUML/origin.js中已经有依赖关系了。
`{ "source" : "AppDelegate", "dest" : "UploadManager" }`表示AppDelegate依赖于Uploadmanager。
将这些文件导入到excel中就可以排序啦。
项目中会出现A依赖B、B又依赖A的情况，这是允许的。

**Comment by wushuyu** [comment]
最后在excel中处理后是这样的列表
![image](https://cloud.githubusercontent.com/assets/15336035/11648685/e434d9ea-9db1-11e5-80ca-d0b6d4cb2bf1.png)

**Comment by kimsungwhee** [comment]
@wushuyu 你可以用右上角的filter来过滤或者是你可以参考一下http://d3js.org/ 自己实现想要的显示效果。
当然你也可以用excel也行。
