### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by ghost** [kimsungwhee/KSHObjcUML#20]
![2016-05-11 7 57 58](https://cloud.githubusercontent.com/assets/18388391/15166099/2d15912a-174e-11e6-8f83-b396fd442a19.png)
![2016-05-11 7 58 13](https://cloud.githubusercontent.com/assets/18388391/15166101/2f0fe174-174e-11e6-9040-6673f216c6a1.png)
4、选择一个项目，点击 Objc-UML 会自动生成并打开生成的类图。
为啥我项目中找不到Objc-UML 这一项呢

**Comment by kimsungwhee** [comment]
如果你是首次安装插件的话，你最好完全退出xcode之后从新打开xcode。应该会出现问你是否载入该插件。如果要是没有出现提示框有可能是你以前直接给拒绝了。你可以reset一下关于是否载入plugin.
你可以看看下面的地址：
http://swanros.com/reset-xcodes-load-bundles-warning/

基本上你的问题就是没有成功载入xcode plugin或者是根本就没有安装成功。
