### ISSUE TITLE
KSHObjcUML如何查看包图、类图的

### ISSUE THREAD

**Issue by ghost** [kimsungwhee/KSHObjcUML#21]
![Uploading 屏幕快照 2016-05-11 下午4.22.01.png…]()
如何使用这个页面查看Uml包图、类图的

**Comment by kimsungwhee** [comment]
你上传的图片没有办法显示

**Comment by ghost** [comment]
点击 Objc-UML 会自动生成一个html，显示动态的类包，如何操作才能得到uml类图

**Comment by kimsungwhee** [comment]
不能得到类图，只能得到类引用关系图。就是你看到的html页面。

**Comment by ghost** [comment]
哦 谢谢
