### ISSUE TITLE
Cannot handle XCode custom locations for Derived Data

### ISSUE THREAD

**Issue by fvvliet** [kimsungwhee/KSHObjcUML#3]
Seems that this plugin cannot deal with custom locations in XCode, see below. Anyone suggestions ?
Thanks
Frank

/Users/myName/Temp/myApp/ObjcUML/script.rb -s "myApp" -t /Users/myName/Temp/myApp/ObjcUML/origin.js

find: /Users/myName/Library/Developer/Xcode/DerivedData: No such file or directory

find: /Users/myName/Library/Caches/appCode*/DerivedData: No such file or directory
There were 0 directories found
Cannot find projects that starts with '"myApp"'

/bin/rm -rf /Users/myName/Temp/myApp/ObjcUML/script.rb

**Comment by kimsungwhee** [comment]
Currently the plugin does not support custom locations for derived data.
I would consider adding this feature in the future. If you need an urgent need for this feature, you can modify the file script.rb.This file exists in ObjcUML.zip, you can unzip the file and modify the look derived data directory.
You can clone this project and directly modify script.rb file mentioned above. Either directly modify xcode plugin file has been installed in the script.rb file.(/Users/#mac user name#/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/Resources/ObjcUML.zip)Modification is completed, zip this file to ObjcUML.zip

thanks.

**Comment by fvvliet** [comment]
great !! fix works as described 

thanks

with regards,

Frank
