### ISSUE TITLE
No graph is generated.

### ISSUE THREAD

**Issue by pmusolino** [kimsungwhee/KSHObjcUML#4]
Hello.

I have a problem with the plugin. I installed it correctly. Runs correctly and generates me the files, but when I open the file "index" in the browser, there is no graphic inside.

I tried with several Xcode projects, but nothing changes.

My Xcode version is 6.1.1
I start the generator from the menu of Xcode. The output is a folder in the xcode project, with the files inside it.

Screenshots:
http://cl.ly/image/293V3U3y382F
http://cl.ly/image/3A3f0b0s1d3c

The path looks correct.
This is the result when i open index.html:
http://cl.ly/image/2B3C3x3a1Z2Y

This is the entire ObjcUML folder: http://cl.ly/381v17093v34

Can you help me?

**Comment by kimsungwhee** [comment]
hello

can you tell me on the debug area what is printed?

First you need to run through at least once a project simulator. This step will create derived data。
Second, make sure your xcode no custom derived data location. Currently the plugin does not support custom derived data location.
Finally, your project name can not be Tests or Pods.

**Comment by pmusolino** [comment]
Hello.

This is the output in the debug area. There are some errors, but if i shift to another project, nothing change.

```
/bin/cp /Users/pmusolino/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/Resources/ObjcUML.zip /Users/pmusolino/Desktop/SocialLogin



/usr/bin/unzip -o -d /Users/pmusolino/Desktop/SocialLogin /Users/pmusolino/Desktop/SocialLogin/ObjcUML.zip


Archive:  /Users/pmusolino/Desktop/SocialLogin/ObjcUML.zip
   creating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/dependency.css  
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/index.html  
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/script.rb  
   creating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/Scripts/
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/Scripts/d3.v3.js  
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/Scripts/d3.v3.min.js  
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/Scripts/d3js-LICENSE  
  inflating: /Users/pmusolino/Desktop/SocialLogin/ObjcUML/Scripts/parse.js  

/bin/rm -rf /Users/pmusolino/Desktop/SocialLogin/ObjcUML.zip



/Users/pmusolino/Desktop/SocialLogin/ObjcUML/script.rb -s "SocialLogin" -t /Users/pmusolino/Desktop/SocialLogin/ObjcUML/origin.js

find: /Users/pmusolino/Library/Caches/appCode*/DerivedData: No such file or directory

There were 0 directories found
Cannot find projects that starts with '"SocialLogin"'

/bin/rm -rf /Users/pmusolino/Desktop/SocialLogin/ObjcUML/script.rb



/usr/bin/open /Users/pmusolino/Desktop/SocialLogin/ObjcUML/index.html
```

**Comment by kimsungwhee** [comment]
I think this issue should be no way to find the cause of derived data.
please check your xcode setting as follow
http://cl.ly/image/2K1Z1w3D1C3a

if derived data setting not by default,this plugin current not support.please change setting by default and try again.

you can download my other project and try it.
https://github.com/kimsungwhee/KSHMosaicCamera
