### ISSUE TITLE
lack some reference.

### ISSUE THREAD

**Issue by Tiger6688** [kimsungwhee/KSHObjcUML#6]
such is my class declaration,

``` objective-C
#import <UIKit/UIKit.h>
#import "UUMessageContentButton.h"
#import "UUMessageFrame.h"
@class UUMessageFrame;
@class UUMessageCell;

@protocol UUMessageCellDelegate <NSObject>
@optional
- (void)headImageDidClick:(UUMessageCell *)cell userId:(NSString *)userId;
- (void)cellContentDidClick:(UUMessageCell *)cell image:(UIImage *)contentImage;
@end
@interface UUMessageCell : UITableViewCell
@property (nonatomic, retain)UILabel *labelTime;
@property (nonatomic, retain)UILabel *labelNum;
@property (nonatomic, retain)UIButton *btnHeadImage;
@property (nonatomic, retain)UUMessageContentButton *btnContent;

@property (nonatomic, retain)UUMessageFrame *messageFrame;

@property (nonatomic, assign)id<UUMessageCellDelegate>delegate;

@end

@interface UUMessageCell ()<UUAVAudioPlayerDelegate>
{
    AVAudioPlayer *player;
    NSString *voiceURL;
    NSData *songData;

    UUAVAudioPlayer *audio;

    UIView *headImageBackView;
}
@end
```

and the generated graph is:  lack the reference of  `UUMessageFrame`
![2015-03-14 1 06 58](https://cloud.githubusercontent.com/assets/8372025/6650416/711a1f9a-ca4b-11e4-84d4-60079958cabb.png)

**Comment by PaulTaykalo** [comment]
@Tiger6688 @kimsungwhee 
https://github.com/PaulTaykalo/objc-dependency-visualizer/releases/tag/0.1
There are new way of dependency generation by using DWARF information and Live Editing, so you can update this plugin with newer version

**Comment by kimsungwhee** [comment]
@PaulTaykalo thanks for your notice. at the future i will update this plugin.

**Comment by kimsungwhee** [comment]
@PaulTaykalo
I had add support for DWARF.thanks.
@Tiger6688 
I think this issue was fixed.please reinstall this plugin.
